builds:
  - binary: faas-ecs
    goos:
      - linux
    goarch:
      - amd64
archive:
  format: zip
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - Merge pull request
    - Merge branch
